gregory094/softlab4

- build_docs.sh
- docs/chapters/chapter02/sablon02.tex
- docs/includes/header.tex
- docs/includes/szglab4.sty
- docs/szoftlab4.tex
Simple script of building the docs added. Docstyle, chapter02 refactored. 
We should find out how to export the artifacts from TravisCI.
> LaTeX build script, style, chapter02. issue#20

- .gitignore
- consults/verbatim.tex
Nézzétek át és valaki merge-elje miután átnéze.
> Első konzultáció jegyzőkönyve

- docs/chapters/chapter02/sablon02.tex
- docs/szoftlab4.tex
Megjegyzés, hogy a JavaDoc sorait kivettem a dokumentációbol, hisz egyenlőre azokra még nagyon nincsen szökség
> [Issue#8] Általános áttekintés hozzáadva dokumentációhoz

- README.md
Branched from one of the issue branches, fixed.
> Updated README.md. Closes #33

- docs/chapters/chapter02/sablon02.tex
> Eröforrásokkal kapcsolatos követelmények.

- docs/chapters/chapter02/sablon02.tex
- docs/includes/szglab4.sty
Szerintem a csapattagok szerepköreinek hiányától eltekintve ez így jó lesz.
ref issue #19
> Projektterv

- build_docs.sh
- docs/chapters/chapter02/sablon02.tex
A második commithoz egy kis magyarázat: valamiért úgy tünik, hogy a LaTeX fel tudja használni a korábbi ideiglenes fájljait, és ez néha azt eredményezi, hogy más eredményt kapunk a `build_docs.sh` script futtatásakor elsö és második alkalomra. Ha töröljük az ideiglenes fájlokat akkor mindenkinek egyezö viselkedést kell tapasztalnia.
> Projekkterv és dokumentáció generálás

- build_docs.sh
- docs/chapters/chapter02/sablon02.tex
- docs/includes/header.tex
- docs/szoftlab4.tex
- texdoclet/javadoc_pre.tex
Apparently not generating a ToC on the first run is completely normal, and you actually have to run the generation 3 times in order to guarantee a perfectly generated document (the ToC on the second run can mess up the page numbers).
> LaTeX generation

- docs/szoftlab4.tex
Kiegészítettem a konzulens nevével és a csapatsorszámunkkal.
> Kijavítottam a hibásan elkészített fedlapot.

- docs/chapters/chapter02/sablon02.tex
- docs/includes/szglab4.sty
Closes #12. Csak akkor mergeljétek, ha szerintetek is elég ennyi referencia / kapcsolat (összehasonlításként régi doksiban ez 1 link)
> Formatting fixes, added references

- docs/chapters/chapter02/sablon02.tex
Closes: #13 
Elkészültem a fukcionális követelmények táblázattal. Valaki zárja le.
> Elkészült Funkcionális követelmények

- docs/includes/szglab4.sty
A slight correction for my previous usecase formatting fix.
> Usecase formatting fix

- build_docs.sh
- docs/svg_preprocess.sh
`command -v` should work on any POSIX compliant shell.
> Script enhancement

- docs/chapters/chapter02/sablon02.tex
> Review fixes

- docs/chapters/chapter03/sablon03.tex
- docs/includes/header.tex
> Added Object Catalogue

- docs/chapters/chapter05/sablon05.tex
- docs/szoftlab4.tex
Kérlek nézzétek át! Írjátok meg, hogy mi a gond, és javítom.
> Pongyola Use-Case leírások készen

- docs/chapters/chapter05/naplo05.tex
> Naplo hozzaadva, nincs kedvem kommitolni rendes szoveget.

- src/main/Main.java
- src/main/agents/Speed.java
These should take care of the Coverity defects for now.
> Coverity fixes

- docs/chapters/chapter06/sablon06.tex
- docs/includes/header.tex
- docs/szoftlab4.tex
Closes #134 and Closes #132 
Ezeket jó lett volna @istvanszoke -nek kipróbálni (meg a benti gépeken se ártott volna)
> Fordítás és futtatás

- src/main/game/Game.java
- src/main/game/Heartbeat.java
- src/main/game/control/GameControllerServer.java
- src/main/game/control/GameControllerSocket.java
- src/main/game/control/GameControllerSocketListener.java
- src/main/game/control/HumanController.java
> Start / pause logic fixes

- docs/chapters/chapter07/sablon07.tex
- docs/szoftlab4.tex
Valaki nézze meg ha rendben akkor mehet a Merge. Kérlek titeket, hogy console-ról a GutHub DDoS miatt.
> Test case-ek beírása dokumentációba

- docs/chapters/chapter07/sablon07.tex
- docs/szoftlab4.tex
Holnap konzi előtt ne merge-eljétek.
> Kimeneti nyelv.

- docs/chapters/chapter07/sablon07.tex
> Bemeneti nyelv

- build_docs.py
- lib/scripts/commands/docs.py
- lib/scripts/commands/file_list.py
- lib/scripts/commands/javadoc.py
- lib/scripts/commands/svg.py
- lib/scripts/debug.py
- lib/scripts/format.py
- lib/scripts/process.py
- lib/scripts/util.py
Tested and works on:
- Linux: Python 2 and 3
- Windows: Python 2
> Build script improvements

- docs/chapters/chapter07/sablon07.tex
Kimeneti es bemeneti nyelv modositasok.
Tesztelés közben rájöttem, hogy milyen parancsok kellenének még a protoba. Beírtam a múltheti doksiba, kérlek nézzétek meg. Bocsi @gregory094 hogy nem vártalak meg vele, de a tesztek megírásához muszáj volt.
@gustorn
> Kimeneti, bemeneti nyelv mod

- docs/chapters/chapter07/sablon07.tex
- docs/chapters/chapter08/sablon08.tex
- docs/szoftlab4.tex
> Elsődleges tesztesetek

- .bootstrap/vagrant_install_ubuntu.sh
- Vagrantfile
install virtualbox and vagrant
`vagrant up`
`vagrant ssh`
> Vagrant added to the project.

- build.bat
> Windows build script

- src/main/agents/AgentVisitor.java
- src/main/agents/Vacuum.java
- src/main/buff/Buff.java
- src/main/buff/Oil.java
- src/main/buff/Sticky.java
- src/main/commands/executes/ChangeDirectionExecute.java
- src/main/commands/executes/ChangeSpeedExecute.java
- src/main/commands/executes/JumpExecute.java
- src/main/commands/queries/ChangeDirectionQuery.java
- src/main/commands/queries/ChangeSpeedQuery.java
- src/main/commands/queries/CleanFieldQuery.java
- src/main/commands/queries/JumpQuery.java
- src/main/commands/queries/UseOilQuery.java
- src/main/commands/queries/UseStickyQuery.java
- src/main/field/Field.java
Summon @Gustorn Please review it and if okay then merge.
> Created mechanism for Vacum to clean up field.

- src/main/Main.java
- src/main/game/GameCreator.java
> Map generation rename

- .bootstrap/vagrant_install_ubuntu.sh
- src/main/game/control/ProtoCommandController.java
- src/main/proto/MissingCommandArgumentException.java
Felmerült egy-két kérdés meg kéne vitatni. Még ne merge-eljetek
> Kisrobot és játékos parancs controller

- src/main/proto/CommandParser.java
- src/main/proto/ProtoCommand.java
Eltér a 7es doksitól, mert nem gondolkoztam akkor és valamiért azt hittem, hogy megkülönböztetjük a commandokat paraméterek alapján is. Ezért átírtam a ragacslerak(field)-et ragacshelyez(field)-re és ugyanígy az olajlerakkal és a listázó parancsokkal
> Új proto parancsok felvétele

- src/main/Main.java
- src/main/agents/Agent.java
- src/main/agents/Robot.java
- src/main/agents/Speed.java
- src/main/agents/Vacuum.java
- src/main/buff/Buff.java
- src/main/buff/Inventory.java
- src/main/commands/AgentCommand.java
- src/main/commands/Command.java
- src/main/field/Field.java
- src/main/game/Game.java
- src/main/game/GameStorage.java
- src/main/game/Map.java
- src/main/game/handle/AgentHandle.java
- src/main/util/DevNull.java
> Serialization and Robot, Vacuum, Field IDs added

- src/main/Main.java
- src/main/game/Game.java
- src/main/game/Heartbeat.java
- src/main/game/control/ProtoCommandController.java
- src/main/proto/CommandParser.java
- src/main/proto/ProtoCommand.java
> Main class prepared for STDIO handling

- src/main/agents/Vacuum.java
- src/main/buff/Oil.java
- src/main/buff/Sticky.java
- src/main/field/Field.java
- src/main/game/Game.java
No instanceof, fixed some errors.
> Map printout

- docs/chapters/chapter11/sablon11.tex
- docs/szoftlab4.tex
> Felület müködési elve

- docs/chapters/chapter11/sablon11.tex
> Objektumkatalógus

- src/main/Main.java
- src/main/agents/Speed.java
- src/main/commands/executes/JumpExecute.java
- src/main/commands/queries/JumpQuery.java
- src/main/commands/transmits/JumpTransmit.java
- src/main/field/DirectionHelper.java
- src/main/field/Displacement.java
- src/main/field/EmptyFieldCell.java
- src/main/field/Field.java
- src/main/field/FinishLineFieldCell.java
- src/main/game/GameCreator.java
- src/main/game/GameSerializer.java
- src/main/proto/TestcaseGenerator.java
- src/resources/maps/ai_test_finish.map
- src/resources/maps/test01.map
- src/resources/maps/test02.map
- src/resources/maps/test03.map
- src/resources/maps/test04.map
- src/resources/maps/test05.map
- src/resources/maps/test06.map
- src/resources/maps/test07.map
- src/resources/maps/test08.map
> Separate Map loader
